# Generated by Django 3.0.5 on 2020-04-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
